// This file is generated by Slice Machine. Update with care!

import Post from './Post';
import Testimonials from './Testimonials';

export {
	Post,
	Testimonials,
};

export const components = {
	post: Post,
	testimonials: Testimonials,
};
